{
//makeStack("prob_t", "BEST t Probability", "jetPt > 500", 50, 0, 1, "prob_t", "prob_t");
//makeStack("prob_W", "BEST W Probability", "jetPt > 500", 50, 0, 1, "prob_W", "prob_W");
//makeStack("prob_Z", "BEST Z Probability", "jetPt > 500", 50, 0, 1, "prob_Z", "prob_Z");
//makeStack("prob_H", "BEST H Probability", "jetPt > 500", 50, 0, 1, "prob_H", "prob_H");
//makeStack("prob_j", "BEST QCD Probability", "jetPt > 500", 50, 0, 1, "prob_j", "prob_j");
//makeStack("prob_b", "BEST b Probability", "jetPt > 500", 50, 0, 1, "prob_j", "prob_j");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && best_class == 1 && prob_W > 0.0", 50, 0, 300, "Wmass", "Wmass");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && best_class == 2 && prob_Z > 0.0", 50, 0, 300, "Zmass", "Zmass");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && best_class == 3 && prob_H > 0.0", 50, 0, 300, "Hmass", "Hmass");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && best_class == 4 && prob_t > 0.0", 50, 0, 300, "tmass", "tmass");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && prob_W < 0.2", 50, 0, 300, "Wmass_pure", "Wmass_pure");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && prob_Z < 0.2", 50, 0, 300, "Zmass_pure", "Zmass_pure");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && prob_H < 0.2", 50, 0, 300, "Hmass_pure", "Hmass_pure");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500 && prob_t < 0.2", 50, 0, 300, "tmass_pure", "tmass_pure");
//makeStack("jetPt", "Jet p_{T} [GeV]", "jetPt > 500", 50, 0, 5000, "pt", "pt");
//makeStack("jetEta", "Jet #eta", "jetPt > 500", 50, -3,3, "eta", "eta");
//makeStack("jetPhi", "Jet #phi", "jetPt > 500", 50, -4,4, "phi", "phi");
//makeStack("jetSDmass", "Jet m_{SD} [GeV]", "jetPt > 500", 50, 0,500,"mass", "mass");

//makeStack("BESTinputs[0]", "Jet m_{SD} [GeV]", "jetPt > 400", 50, 0, 300, "BESTin_sdmass", "BESTin_sdmass");
//makeStack("BESTinputs[1]", "Jet #tau_{32} [GeV]", "jetPt > 400", 50, 0,1, "BESTin_tau32", "BESTin_tau32");
//makeStack("BESTinputs[2]", "Jet #tau_{21} [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_tau21", "BESTin_tau21");
//makeStack("BESTinputs[3]", "Jet FW Moment 1 (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm1_t", "BESTin_fwm1_t");
//makeStack("BESTinputs[4]", "Jet FW Moment 2 (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm2_t", "BESTin_fwm2_t");
//makeStack("BESTinputs[5]", "Jet FW Moment 3 (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm3_t", "BESTin_fwm3_t");
//makeStack("BESTinputs[6]", "Jet FW Moment 4 (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm4_t", "BESTin_fwm4_t");
//makeStack("BESTinputs[7]", "Isotropy (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_isotropy_t", "BESTin_isotropy_t");
//makeStack("BESTinputs[8]", "Aplanarity (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_aplanarity_t", "BESTin_aplanarity_t");
//makeStack("BESTinputs[9]", "Sphericity (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_sphericity_t", "BESTin_sphericity_t");
//makeStack("BESTinputs[10]", "Thrust (Top Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_thrust_t", "BESTin_thrust_t");
//makeStack("BESTinputs[11]", "Jet FW Moment 1 (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm1_W", "BESTin_fwm1_W");
//makeStack("BESTinputs[12]", "Jet FW Moment 2 (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm2_W", "BESTin_fwm2_W");
//makeStack("BESTinputs[13]", "Jet FW Moment 3 (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm3_W", "BESTin_fwm3_W");
//makeStack("BESTinputs[14]", "Jet FW Moment 4 (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm4_W", "BESTin_fwm4_W");
//makeStack("BESTinputs[15]", "Isotropy (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_isotropy_W", "BESTin_isotropy_W");
//makeStack("BESTinputs[16]", "Aplanarity (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_aplanarity_W", "BESTin_aplanarity_W");
//makeStack("BESTinputs[17]", "Sphericity (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_sphericity_W", "BESTin_sphericity_W");
//makeStack("BESTinputs[18]", "Thrust (W Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_thrust_W", "BESTin_thrust_W");
//makeStack("BESTinputs[19]", "Jet FW Moment 1 (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm1_Z", "BESTin_fwm1_Z");
//makeStack("BESTinputs[20]", "Jet FW Moment 2 (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm2_Z", "BESTin_fwm2_Z");
//makeStack("BESTinputs[21]", "Jet FW Moment 3 (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm3_Z", "BESTin_fwm3_Z");
//makeStack("BESTinputs[22]", "Jet FW Moment 4 (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm4_Z", "BESTin_fwm4_Z");
//makeStack("BESTinputs[23]", "Isotropy (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_isotropy_Z", "BESTin_isotropy_Z");
//makeStack("BESTinputs[24]", "Aplanarity (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_aplanarity_Z", "BESTin_aplanarity_Z");
//makeStack("BESTinputs[25]", "Sphericity (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_sphericity_Z", "BESTin_sphericity_Z");
//makeStack("BESTinputs[26]", "Thrust (Z Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_thrust_Z", "BESTin_thrust_Z");
//makeStack("BESTinputs[27]", "Jet FW Moment 1 (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm1_H", "BESTin_fwm1_H");
//makeStack("BESTinputs[28]", "Jet FW Moment 2 (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm2_H", "BESTin_fwm2_H");
//makeStack("BESTinputs[29]", "Jet FW Moment 3 (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm3_H", "BESTin_fwm3_H");
//makeStack("BESTinputs[30]", "Jet FW Moment 4 (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_fwm4_H", "BESTin_fwm4_H");
makeStack("BESTinputs[31]", "Isotropy (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_isotropy_H", "BESTin_isotropy_H");
makeStack("BESTinputs[32]", "Aplanarity (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_aplanarity_H", "BESTin_aplanarity_H");
makeStack("BESTinputs[33]", "Sphericity (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_sphericity_H", "BESTin_sphericity_H");
makeStack("BESTinputs[34]", "Thrust (H Frame) [GeV]", "jetPt > 400", 50, 0, 1, "BESTin_thrust_H", "BESTin_thrust_H");
makeStack("BESTinputs[35]", "Maximum Subjet CSV", "jetPt > 400", 50, 0, 1, "BESTin_maxbdisc", "BESTin_maxbdisc");
makeStack("BESTinputs[36]", "Subjet 1 CSV", "jetPt > 400", 50, 0, 1, "BESTin_bdisc1", "BESTin_q");
makeStack("BESTinputs[37]", "Subjet 2 CSV", "jetPt > 400", 50, 0, 1, "BESTin_bdisc2", "BESTin_q");
makeStack("BESTinputs[38]", "Jet Charge", "jetPt > 400", 50, -2, 2, "BESTin_q", "BESTin_q");

}
